### ISSUE TITLE
Add environment variable support to helm chart

### ISSUE THREAD

**Issue by jtamas96** [CrunchyData/postgres-operator-examples#251] opened 2024-01-19 09:17 UTC
Currently there is no option to add extra environment variables to the PGO deployment via Helm chart install.
This would be needed to for example enable feature gates.

**Comment by benjaminjb** [comment] 2024-06-06 20:57
I'm going to close this as a duplicate of https://github.com/CrunchyData/postgres-operator-examples/issues/262, but we do have this in our backlog.

**Closed by benjaminjb** 2024-06-06 20:57 UTC
